a = int(input('Enter a number'))
b = int(input('Enter another numer'))
print('sum:' ,a+b)
print('sub:' ,a-b)
print('mul:' ,a*b)
print('int div:' ,a//b)
print('float div :', a/b)
print('mod:' ,a%b)
print('power:',a**b)